"""
RAG Retriever setup (Context Stuffing).

For the MVP, instead of a complex vector database and CrossEncoder,
we simply load the Markdown file generated by ingest.py and return
it in full. This is much faster and simpler for docs that easily fit
in the LLM context window.
"""

from __future__ import annotations

import logging
from pathlib import Path

logger = logging.getLogger(__name__)


def retrieve_and_rerank(query: str, top_n: int = 3) -> str:
    """Retrieve context.
    
    For Context Stuffing, we ignore the query and just return the full doc.
    """
    doc_path = Path("automigrate/rag/data/angular_control_flow.md")
    
    if not doc_path.exists():
        logger.warning(f"Doc file not found at {doc_path}. Did you run 'automigrate ingest'?")
        return "Context: @if (data$ | async; as data) { ... }"
        
    return doc_path.read_text(encoding="utf-8")
